# Generated by Django 4.2.2 on 2024-03-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_author_alter_book_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(null=True, upload_to='books/'),
        ),
    ]
