# Generated by Django 4.2.2 on 2024-03-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
    ]
